steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_IMAGE_NAME:$COMMIT_SHA'
      - '-t'
      - '$_IMAGE_NAME:$BRANCH_NAME'
      - '-f'
      - './api/Dockerfile'
      - ./api/
    id: Build
    timeout: 600s
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$COMMIT_SHA'
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_IMAGE_NAME:$BRANCH_NAME'
    id: Push
images:
  - '$_IMAGE_NAME:$COMMIT_SHA'
  - '$_IMAGE_NAME:$BRANCH_NAME'
options:
  substitutionOption: ALLOW_LOOSE
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - bibleserver

