name: Test build

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: DEV
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Fix up files for CI
      run: |
        cp -v "firebase/functions/example.runtimeconfig.json" "firebase/functions/.runtimeconfig.json"
        cp -v "client/src/configs/config.json.template" "client/src/configs/config.json"
    - name: Run tests
      working-directory: ./firebase/functions
      run: |
        npm i
        npm test
    - name: npm install and build (client)
      working-directory: ./client
      run: |
        npm ci
        npm run build
    - name: npm install and build (functions)
      working-directory: ./firebase/functions
      run: |
        npm ci
        npm run build
